image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew

build-script:
  - ./gradlew test --Dselenide.headless=true